# Generated by Django 5.2.4 on 2025-10-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('battery_level', models.IntegerField(default=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('power_state', models.BooleanField(default=False)),
                ('fan_speed', models.IntegerField(default=1)),
                ('angle', models.FloatField(default=0.0)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FilterStatus',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('dust_accumulated', models.FloatField(default=0.0)),
                ('condition', models.CharField(default='good', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.device')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('dust_density', models.FloatField()),
                ('co2_level', models.FloatField()),
                ('ir_detected', models.BooleanField(default=False)),
                ('heatmap_temp', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device')),
            ],
        ),
    ]
