# Generated by Django 5.0.6 on 2026-02-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "device_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("battery_level", models.IntegerField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=100, null=True)),
                ("power_state", models.BooleanField(default=False)),
                ("fan_speed", models.IntegerField(default=1)),
                ("angle", models.FloatField(default=0.0)),
                ("last_sync", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(default="default_team", max_length=100)),
                ("team_password", models.CharField(default="0000", max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("device_id", models.CharField(blank=True, max_length=50, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FilterStatus",
            fields=[
                ("filter_id", models.AutoField(primary_key=True, serialize=False)),
                ("dust_accumulated", models.FloatField(blank=True, null=True)),
                ("condition", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.device"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                ("sensor_id", models.AutoField(primary_key=True, serialize=False)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("dust_density", models.FloatField(blank=True, null=True)),
                ("co2_level", models.FloatField(blank=True, null=True)),
                ("ir_detected", models.BooleanField(default=False)),
                ("heatmap_temp", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.device"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamDevice",
            fields=[
                ("team_device_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.device"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamUser",
            fields=[
                ("team_user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("sub_admin", "Sub Admin"),
                            ("user", "User"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
    ]
