# Generated by Django 5.0.6 on 2025-11-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="ip_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="filterstatus",
            name="condition",
            field=models.CharField(default="Good", max_length=50),
        ),
        migrations.AlterField(
            model_name="filterstatus",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.device",
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.device",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="device_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
