# Generated by Django 5.0.6 on 2026-02-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="heatmap_temp",
        ),
        migrations.AddField(
            model_name="device",
            name="mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("rotate", "Rotate"),
                    ("following", "Following"),
                    ("tracking", "Tracking"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
