# Generated by Django 5.0.6 on 2025-11-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_device_user_alter_device_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="battery_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="fan_speed",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="network_sync",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="part_connected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="user_detected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="voice_command",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="co2_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="dust_density",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="heatmap_temp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
